Проверка рабочего процесса
htmlacademy-javascript/267675-keksobooking-26 pull request #1
Opened 2022-06-01 12:40 UTC by valek00794

---
:mortar_board: [Проверка рабочего процесса](https://up.htmlacademy.ru/javascript/26/user/267675/tasks/5)

2022-06-01 18:06 UTC, Dima-Dim requested changes

2022-06-01 18:06 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Отредактируй, пожалуйста, строку Наставник чтобы было по аналогии со строкой Студент. Для этого нужно добавить ссылку на мой профиль https://htmlacademy.ru/profile/dima

2022-06-01 18:59 UTC, valek00794 commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Отредактировано согласно замечанию

2022-06-02 07:10 UTC, Dima-Dim approved these changes

2022-06-02 07:10 UTC, merged