Нужно больше функций
htmlacademy-javascript/267675-keksobooking-26 pull request #2
Opened 2022-06-03 09:38 UTC by valek00794

2022-06-04 18:20 UTC, Dima-Dim requested changes

2022-06-04 18:20 UTC, Dima-Dim commented on js/main.js
> +  } else {
https://up.htmlacademy.ru/javascript/26/criteries#d18

2022-06-04 18:20 UTC, Dima-Dim commented on js/main.js
> +function randomNumber(min, max, decimal) {
https://up.htmlacademy.ru/javascript/26/criteries#b6

2022-06-04 19:03 UTC, valek00794 commented on js/main.js
> +function randomNumber(min, max, decimal) {
Исправлено

2022-06-04 19:03 UTC, valek00794 commented on js/main.js
> +  } else {
Исправлено

2022-06-05 17:13 UTC, Dima-Dim reviewed
А если ни первый, ни второй if не сработают как тот, кто это будет использовать узнает что пошло не так? :)
Можешь доработать это в следующем задании.

2022-06-05 17:13 UTC, merged