Модуляция
htmlacademy-javascript/267675-keksobooking-26 pull request #4
Opened 2022-06-11 10:18 UTC by valek00794

2022-06-12 04:51 UTC, Dima-Dim requested changes

2022-06-12 04:51 UTC, Dima-Dim commented on js/data.js
> +  const LATITUDE = getRandomNumber(35.65,35.7,5);
https://up.htmlacademy.ru/javascript/26/criteries#d19
Ну и за одно, хорошо бы визуально разделять передаваемые в функцию значения пробелами.

2022-06-12 04:51 UTC, Dima-Dim commented on js/data.js
> +  const arrayObject = [];
https://up.htmlacademy.ru/javascript/26/criteries#b5 не нужно использовать для  названий массивов слово array, а для объектов object. Это увеличивает длинную названий, но для того чтобы было понятно что внутри, у нас есть договорённости по неймингу.

2022-06-12 04:51 UTC, Dima-Dim commented on js/data.js
> +  return arrayObject;
Тут мы возвращаем массив объектов.

2022-06-12 04:51 UTC, Dima-Dim commented on js/data.js
> +const doneArray = createObjectArray(COUNT_OBJECTS);
Значит тут в doneArray, тоже ужасное название, массив объектов.

2022-06-12 04:51 UTC, Dima-Dim commented on js/main.js
> +doneArray();
А здесь мы пытаемся выполнить массив объектов и получаем заслуженную ошибку:
```
Uncaught TypeError: doneArray is not a function
    at main.js:2:1
(anonymous) @ main.js:2
```
https://htmlacademy-javascript.github.io/267675-keksobooking-26/4/

2022-06-12 05:44 UTC, valek00794 commented
Замечания исправлены

2022-06-13 06:09 UTC, Dima-Dim commented on js/data.js
> +const OFFER_PHOTOS  = [
Для чего лишний пробел? :)

2022-06-13 06:09 UTC, Dima-Dim commented on js/data.js
> +  const data = [];
https://up.htmlacademy.ru/javascript/26/criteries#b5
Тебе же самому потом будет не понятно, что это data такая :)

2022-06-13 06:09 UTC, merged